### PR TITLE
Bugfix/reset dt consistently new

### PR DESCRIPTION
**Pull request by rd1042**
This is a fix for [#33]; I've tested and confirmed (by forcing restart_time_step to .true.) that if the timestep needs be reset, the changes to g and phi are discarded and the timestep is re-done (for both flip_flop = .false. and flip_flop = .true.)

### CODE REVIEW

**Comment by DenSto** [comment]
The logic in advance_explicit_rk* doesn't seem quite right... if restart_time_step = .true., then it restarts the loop. Shouldn't it escape the function and retry the entire timestep?

**Comment by rd1042** [comment]
> The logic in advance_explicit_rk* doesn't seem quite right... if restart_time_step = .true., then it restarts the loop. Shouldn't it escape the function and retry the entire timestep?

It could do this. My thought was that by repeating the loop in advance_explicit_rk* until there's a code_dt which goes through all stages of the RK scheme without being reset, the timestep only gets restarted once there's a code_dt which works for all steps of RK scheme. This may save a little time, since it avoids unnecessary calls advance_implicit, at the expense of causing unnecessary calls to advance_explicit.

**Comment by DenSto** [comment]
In practice though, I haven't seen the timestep being updated more than once at a time, so I think the extra calls to solve_gke are likely superfluous. What's your experience with timestep changes? Have you seen it being changed more than once per timestep?

**Comment by rd1042** [comment]
This is fair enough. I'm not sure if I've seen the code_dt getting updated multiple occasions per timestep (in cases when the simulation blows up, I've seen code_dt changing  O(1 time) per timestep, but I suppose such simulations are doomed anyway, and since the response matrix is recalculated whenever reset_dt is called this is likely to dominate the simulation cost). I'll make the change you suggest and re-PR

**Comment by HanneThienpondt** [comment]
I have incorporated this pull request in the CFL_updates pull request, since both updates are about the time step/code_dt/cfl_dt.

**Pull request closed without merging**
