### PR TITLE
Stellarator symmetric twist and shift BC (bug and new functionality)

### PR DESCRIPTION
**Pull request by AntonioG-Jerez**
i) Bug in the stellarator symmetric twist and shift BC factor fixed.

ii) Now it is possible to choose automatically the length of the flux tube depending on the desired $dkx/dky$ if using stellarator symmetric twist and shift BC. This is done via the new input variable 'dkx_over_dky'.

### CODE REVIEW

**Comment by DenSto** [comment]
I find it a little weird that `dkx_over_dky` needs to live in zgrid.f90, while it feels like it should live more in kt_grids.f90, especially since one can set dkx and dky separately, at least in some situations. Is this a problem of awkward dependencies?

**Comment by AntonioG-Jerez** [comment]
`dkx_over_dky` is defined in zgrid.f90 because it is used in geo/stella_geometry.f90 in order to select the new length of the flux tube. If I am not mistaken the module kt_grids is loaded after the geometry of the flux tube is created, isn't it?

**Comment by DenSto** [comment]
Yeah, that's where the difficulty lies, isn't it? I'll do the pull, but in the future we may want to think of a better way of organizing these parameters.

**Comment by AntonioG-Jerez** [comment]
Yes I agree with you. This is an 'easy' way of making this option work. However, it would be interesting to organize these parameters in the future in a better way.

**Pull request merged**
