### PR TITLE
Stellarator symmetric Boundary Conditions added

### PR DESCRIPTION
**Pull request by AntonioG-Jerez**
Generalized twist and shift boundary conditions implemented. Accessible through the new input variables:

- 'twist_shift_option' which can take the values 'standard' (set by default) and 'stellarator'.
- 'grad_x_grad_y_zero' (set by default to 1E-5).

The option to select the desired kx_min/ky_min ratio so that the code chooses by itself  the length of the flux tube is not implemented yet.

### CODE REVIEW

**Comment by DenSto** [comment]
Compilation fails:

```
/home/runner/work/stella/stella/geo/stella_geometry.f90:425:8:

  425 |     if (vmec_chosen==.true.) then
      |        1
Error: Logicals at (1) must be compared with .eqv. instead of ==
make: *** [Makefile:318: stella_geometry.o] Error 1
```

**Comment by DenSto** [comment]
Also, what does `twist_shift_option_periodic` do?

**Comment by AntonioG-Jerez** [comment]
Changed on AntonioG-Jerez/stella. It should compile now (it also compiled in Marconi as it was written before).

`twist_shift_option_periodic` is the value that `twist_shift_option` takes if `shat <= shat_zero` (if using std twist and shift BC) or if `grad_x_grad_y_end <= grad_x_grad_y_zero` (if using stellarator periodic twist and shift). In that cases, the code imposes `dkx=dky` in `kt_grids.f90` and `periodic=.true`. in `extended_zgrid.f90`

**Review by DenSto — COMMENTED** [review]
A few more questions:
In kt_grids, lines 270-277, you removed the factor of  (2*nperiod - 1) in the defnition of dkx (this change may have happened in  newer branch you were working with). I still think it needs to be there. The question is, should it be there for the stellarator version as well?

In lines 307-311, you removed the check that shat should be large enough when setting theta0. What's the rational behind this?

**Comment by AntonioG-Jerez** [comment]
Yes, that factor of (2*nperiod-1) in the definition of dkx belongs to a newer branch. I don't think that should be added to the stellerator symmetric boundary conditions. Actually it does not matter since (in contrast to tokamaks) nperiod = 1 for a stellerator geometry always since you cannot assume (in general) periodicity along a field line. 

About the second question, theta0 should be defined as theta0=dkx/(dky shat) even if shat < shat0 because the perpendicular wavenumber (line 209 in dist_fn.f90) is defined explicetely as a function of theta0 times the geometric quantities (gds21, gds22) which are normalized using shat independently of its value (even if shat < shat0) if the equilibrium is read from a VMEC output (lines 337-339 in stella_geometry.f90). So, in order to compute the perpendicular wavenumbers you desire, theta0 should be defined as theta0=dkx/(dky shat) even if shat<shat0

**Comment by DenSto** [comment]
OK. That makes sense.  I'll just request some minor changes and then I'll pull

**Review by DenSto — CHANGES_REQUESTED** [review]
1. restore (2*nperiod-1) for the standard twist and shift boundary condition
2. rename twist_shift_option_new to something more informative. twist_shift_option_mirror maybe, or _stellarator?
3. Make sure your indentations are three spaces. I'm not so picky when it comes to alignment after lines that end with '&', so don't worry about those.

**Comment by AntonioG-Jerez** [comment]
Changed. I have renamed the variable `twist_shift_option_new` to `twist_shift_option_stellarator`.

**Pull request merged**
