### PR TITLE
Auto-apply `fprettify`

### PR DESCRIPTION
**Pull request by ZedThree**
This is a _big_ PR, touching basically everything. I recommend going to "Files changed", then click the cog symbol and "Hide whitespace"... it will still be big, just not quite as massive

image

This adds `.fprettify.conf` config file for `fprettify` with the following options:

- indent to 3 spaces
- whitespace around operators, print/read, plus/minus, muliply/divide
- convert relational operators to C-style, e.g. `.le.` to `<=`

Unfortunately, `fprettify` can't split long lines, although it does have a `line-length` option. I've set this to 150, otherwise it is _incredibly_ noisy.
Also unfortunately, it seems to choke on converting keywords etc to lowercase, so I've not enabled that. I have run that once, so it's been applied to at least some files.

I recommend running it like:

```bash
fprettify --config-file .fprettify.conf --silent $(git ls-files | grep -E "\.f[p9][p0]")
```

or just leaving it to Github Actions which will run it on every push to Github, and automatically commit any changes. It takes about a minute to run on all files.

### CODE REVIEW

**Comment by DenSto** [comment]
Right now, the change also adds spaces around arguments in function calls, array incides, etc... I think that might be overkill. Can this be removed?

**Comment by ZedThree** [comment]
Could you point to an example that you don't like? It should be formatting like this:

```fortran
lhs = func(arg1, arg2(:, 0))
```

which is a pretty typical standard, and seems to be the most common formatting in the codebase already.

**Comment by DenSto** [comment]
I suppose what I was thinking of was something like 

`real, dimension (:,:) :: some_array`

but I suppose this is a rather minor annoyance on a change that would greatly benefit the code. I'm happy to pull it, but you may need to re-run the script with the most up-to-date version of the code?

**Comment by ZedThree** [comment]
Ah yes, that's a fair point. That does seem like overkill in that case, but I suspect it's collateral damage and there's not a great deal we can do about it.

Yep, I'll try and get this updated this afternoon.

**Pull request merged**
